name: ci
on:
  - pull_request
  - push

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 14
          - 16
          - 18
        exclude:
          - os: windows-latest
            node_version: 14
          - os: macos-latest
            node_version: 14
        include:
          - os: windows-2019
            node_version: 14
          - os: macos-13
            node_version: 14
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('package.json') }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Setup python
        if: matrix.node_version == 14
        # Old versions of Node bundle old versions of npm.
        # Old versions of npm bundle old versions of node-gyp.
        # Old versions of node-gyp are incompatible with Python 3.11+.
        # Install older Python (Python 3.10) as a workaround.
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python setuptools
        # This is needed for Python 3.12+, since many versions of node-gyp
        # are incompatible with Python 3.12+, which no-longer ships 'distutils'
        # out of the box. 'setuptools' package provides 'distutils'.
        run: |
          python3 -m venv CI_venv
          source CI_venv/bin/activate
          python3 -m pip install setuptools

      - name: Install dependencies
        run: |
          source CI_venv/bin/activate
          npm install

      - name: Lint
        run: npm run standard

      - name: Run tests
        run: |
          npm run test:node
          npm run test:native

  Skip:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI ðŸš«
        run: echo skip ci
